/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/demo02': RouteRecordInfo<'/demo02', '/demo02', Record<never, never>, Record<never, never>>,
    '/demo03': RouteRecordInfo<'/demo03', '/demo03', Record<never, never>, Record<never, never>>,
    '/demo04': RouteRecordInfo<'/demo04', '/demo04', Record<never, never>, Record<never, never>>,
    '/demo05': RouteRecordInfo<'/demo05', '/demo05', Record<never, never>, Record<never, never>>,
    '/demo06': RouteRecordInfo<'/demo06', '/demo06', Record<never, never>, Record<never, never>>,
    '/examples/datav/01/': RouteRecordInfo<'/examples/datav/01/', '/examples/datav/01', Record<never, never>, Record<never, never>>,
    '/examples/datav/01/components/Chart01/CirclePoint': RouteRecordInfo<'/examples/datav/01/components/Chart01/CirclePoint', '/examples/datav/01/components/Chart01/CirclePoint', Record<never, never>, Record<never, never>>,
    '/examples/datav/01/components/Chart02/Panel1': RouteRecordInfo<'/examples/datav/01/components/Chart02/Panel1', '/examples/datav/01/components/Chart02/Panel1', Record<never, never>, Record<never, never>>,
    '/examples/datav/01/components/Chart02/Panel2': RouteRecordInfo<'/examples/datav/01/components/Chart02/Panel2', '/examples/datav/01/components/Chart02/Panel2', Record<never, never>, Record<never, never>>,
    '/examples/datav/01/components/Chart02/Panel3': RouteRecordInfo<'/examples/datav/01/components/Chart02/Panel3', '/examples/datav/01/components/Chart02/Panel3', Record<never, never>, Record<never, never>>,
  }
}
