/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BasicChart: typeof import('./../components/BasicChart/index.vue')['default']
    Border01: typeof import('./../components/Border/01/Index.vue')['default']
    Border01Small: typeof import('./../components/Border/01/Small.vue')['default']
    Border02: typeof import('./../components/Border/02/Index.vue')['default']
    DataVBorderBox7: typeof import('@kjgl77/datav-vue3')['BorderBox7']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
